"""create reference tables

Revision ID: 0284347716b0
Revises: 2d3db133ef29
Create Date: 2026-04-26 20:56:41.012388

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0284347716b0'
down_revision: Union[str, None] = '2d3db133ef29'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ref_abilities',
    sa.Column('code', sa.String(length=8), nullable=False),
    sa.Column('name_ru', sa.String(length=64), nullable=False),
    sa.Column('short_ru', sa.String(length=8), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('ref_backgrounds',
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name_ru', sa.String(length=64), nullable=False),
    sa.Column('description_ru', sa.Text(), nullable=False),
    sa.Column('ability_scores', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('granted_skills', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('feat_ru', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('ref_classes',
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name_ru', sa.String(length=64), nullable=False),
    sa.Column('description_ru', sa.Text(), nullable=False),
    sa.Column('hit_die', sa.Integer(), nullable=False),
    sa.Column('primary_abilities', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('saving_throw_abilities', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('skill_choices_count', sa.Integer(), nullable=False),
    sa.Column('skill_options', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('ref_races',
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name_ru', sa.String(length=64), nullable=False),
    sa.Column('description_ru', sa.Text(), nullable=False),
    sa.Column('size', sa.String(length=16), nullable=False),
    sa.Column('speed', sa.Integer(), nullable=False),
    sa.Column('traits', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('ref_skills',
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name_ru', sa.String(length=64), nullable=False),
    sa.Column('ability_code', sa.String(length=8), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ref_skills')
    op.drop_table('ref_races')
    op.drop_table('ref_classes')
    op.drop_table('ref_backgrounds')
    op.drop_table('ref_abilities')
    # ### end Alembic commands ###
