"""create characters table

Revision ID: 99625dcd578b
Revises: 0284347716b0
Create Date: 2026-04-27 05:08:27.140517

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '99625dcd578b'
down_revision: Union[str, None] = '0284347716b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('characters',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('alignment', sa.String(length=32), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('race_code', sa.String(length=32), nullable=False),
    sa.Column('class_code', sa.String(length=32), nullable=False),
    sa.Column('background_code', sa.String(length=32), nullable=False),
    sa.Column('ability_scores', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('background_bonuses', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('chosen_skills', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['background_code'], ['ref_backgrounds.code'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['class_code'], ['ref_classes.code'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['race_code'], ['ref_races.code'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_characters_user_id'), 'characters', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_characters_user_id'), table_name='characters')
    op.drop_table('characters')
    # ### end Alembic commands ###
