"""create campaigns and members

Revision ID: 9df6359e88ec
Revises: fd96880601ac
Create Date: 2026-04-27 15:45:02.597541

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9df6359e88ec'
down_revision: Union[str, None] = 'fd96880601ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaigns',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('master_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('invite_code', sa.String(length=16), nullable=False),
    sa.Column('allowed_races', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('allowed_classes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('max_level', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['master_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaigns_invite_code'), 'campaigns', ['invite_code'], unique=True)
    op.create_index(op.f('ix_campaigns_master_id'), 'campaigns', ['master_id'], unique=False)
    op.create_table('campaign_members',
    sa.Column('campaign_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('character_id', sa.UUID(), nullable=True),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('campaign_id', 'user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('campaign_members')
    op.drop_index(op.f('ix_campaigns_master_id'), table_name='campaigns')
    op.drop_index(op.f('ix_campaigns_invite_code'), table_name='campaigns')
    op.drop_table('campaigns')
    # ### end Alembic commands ###
