"""add is_archived to characters

Revision ID: fd96880601ac
Revises: 99625dcd578b
Create Date: 2026-04-27 05:20:15.950395

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd96880601ac'
down_revision: Union[str, None] = '99625dcd578b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        'characters',
        sa.Column(
            'is_archived',
            sa.Boolean(),
            nullable=False,
            server_default=sa.false(),
        ),
    )
    # Drop the server_default so future inserts use Python-side default only.
    op.alter_column('characters', 'is_archived', server_default=None)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('characters', 'is_archived')
    # ### end Alembic commands ###
